### ISSUE TITLE
Bug:  Changing ship from Hunter to default ship: null reference exception

### ISSUE THREAD

**Issue by theotherjay** [MovingBlocks/DestinationSol#10]
The exception occurred at the starting port.  I attempted to change to default ship and received the error in the attached screenshot.  I was able to reproduce this a second time with the same prevship.ini.  I"ve attached the screenshot and the prevship.ini containing the hunter ship configuration.

prevship.ini
hull=desertMedium
money=2104
items=bulletClip bulletClip bulletClip bulletClip bulletClip bulletClip bulletClip bulletClip bulletClip bulletClip bulletClip bulletClip bulletClip rep rep rep rep rep rep rep rep rep rep rep rep rep rep rep rep rep rep rep rep rep rep rep teleportCharge teleportCharge teleportCharge teleportCharge teleportCharge teleportCharge teleportCharge teleportCharge teleportCharge teleportCharge fixedGun a4 s3 fixedShotGun shellClip shellClip shellClip shellClip shellClip shellClip shellClip shellClip shellClip fixedGun plasmaGun plasmaClip plasmaGun s1 plasmaGun unShieldCharge s2 blaster 

![huntertodefaultship-nullreferenceexception](https://cloud.githubusercontent.com/assets/6021517/7425382/b967c0e8-ef7d-11e4-9de1-3ecd69858f9c.jpg)

**Comment by Cervator** [comment]
Thanks! These we do need on GitHub :-)
