### ISSUE TITLE
Split apart menu background + logo, update to new logo

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#100]
TrekMarvel provided a set of nice new logos in the forum: http://forum.terasology.org/threads/a-brand-new-logo.1545

Trouble is without a pure black background any logo may look funny / clash with the black background. We should likely split apart the background from the logo, set the background image to fill the whole background of the menu, then add the logo as an overlay above the buttons.

I've tried updating the Android logos and such, that seems to work OK. May not have found the spot determining the icon for the windows on PC yet.

**Comment by SimonC4** [comment]
I think the Windows executable used Launch4j, which is a tool for wrapping Java applications distributed as jars in lightweight Windows native executables.

More information on Launch4j: http://launch4j.sourceforge.net/
This Gradle plugin might be useful: https://github.com/TheBoegl/gradle-launch4j

**Comment by Cervator** [comment]
Oh that's right. Thanks :-)

I *think* I was even seeing the old icon on the game launched via source, so may still need to hunt that piece. Icon on Android in its task manager was updated, so that was cool to see.

**Comment by crazywolf132** [comment]
The game will work fine without a pure black background. I did some testing and it is fine.

**Comment by crazywolf132** [comment]
Working on PR now.

**Comment by vampcat** [comment]
Closing, as completed by #145 .
