### ISSUE TITLE
Game lag causes audio problems

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#102]
I'm not sure if this is new with the soundtrack but it may be easier to detect now that there's more audio active.

Reported at http://steamcommunity.com/app/342980/discussions/1/352788552267722914/ specifically with the music going crazy on a Windows 10 system, happening some minutes into the game in laggy situations. Music playing in the menu is fine.

I experienced something similar while playing on Android and an enemy ship seemingly got stuck under the planet surface, yet it was still very eager to shoot me. Being that it was up against a wall the sfx from firing/landing hits were playing excessively and my phone nearly locked up from the lag with audio again sounding terrible due to the lag.

I wonder if there is something we can do to either limit audio being played if too much triggers or somehow isolate the playing somehow (background thread?) to where game lag won't kill it.

@SimonC4 and @Rulasmur - ping! Since the two of you worked with the MusicManager :-)

**Comment by SimonC4** [comment]
Oh that's no good. I'm not currently set up to dev, but I can add my thoughts.

Looking at the [documentation](https://github.com/libgdx/libgdx/wiki/Streaming-music) 

> Music instances are heavy, you should usually not have more than one or two at most loaded.

It looks like the [constructor](https://github.com/MovingBlocks/DestinationSol/blob/develop/main/src/org/destinationsol/game/sound/MusicManager.java#L52) is loading four instances, which might be the problem. That would be my starting point anyway.

**Comment by Cervator** [comment]
Oh good catch. So probably set init to just load the menu piece, then dispose and load the others as-needed. That seems a fair change. Thanks :-)
