### ISSUE TITLE
README Build instructions unclear

### ISSUE THREAD

**Issue by KelsonBall** [MovingBlocks/DestinationSol#103]
I have been interested in this project for a while but I am a C# developer who is fairly new to Java/IntelliJ and I have absolutely no idea what "run gradlew idea" means. Is there a terminal inside intelliJ? Am I supposed to run that from cmd.exe, powershell, or a bash terminal? Does it need to be run from the project's root directory or from anywhere? A google search was not particularly helpful.

**Comment by SimonC4** [comment]
Hi @KelsonBall 

Thanks for feedback. You'll need to run that from the command prompt (Windows) or terminal (Mac). It needs to be run from the project directory.

**Comment by Cervator** [comment]
Hey there, welcome :-)

`gradlew idea` can be run either from the Terminal window inside IntelliJ (which puts you into the right directory automatically) or from cmd/powershell/bash after `cd`ing to the workspace root directory.

Gradle (auto-initialized and prepared by the `gradlew` script) is much like Maven and other build tools, so it works on whatever is in the dir you start in.

**Comment by Cervator** [comment]
Added a slight bit of clarification to the readme just now, hopefully that helps! :-)

Closing as complete for now, if you have other doc suggestions or questions @KelsonBall please do ask

Will be released soon with v1.4.1
