### ISSUE TITLE
Tweak tutorial to highlight items to drop, un-equip, and equip?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#106]
As noted in the newly posted Lets Play series on the Tutorial chapter the tutorial doesn't actually highlight valid items to drop, un-equip, or equip - despite the rest of the tutorial highlighting buttons really well. Probably because there's no guarantee valid items are present since the player can drop too much or something.

Maybe we can for the tutorial disable non-highlighted options so you can't get stuck in a bad state.

http://steamcommunity.com/sharedfiles/filedetails/?id=734348436

**Comment by crazywolf132** [comment]
Why are you guys so far behind? Is no one working on this anymore?

**Comment by Cervator** [comment]
Closing as improved enough by #121
