### ISSUE TITLE
Mercs do not  shoot at enemies

### ISSUE THREAD

**Issue by JGelfand** [MovingBlocks/DestinationSol#109]
I've been looking at this for a bit, and intend to fix it eventually, but if anyone's interested here are my notes so far:

- The AiPilot class contains a Shooter
- the Shooter does some math, but does not have guns
- the Shooter sets a variable called myShoot
- AiPilot::IsShoot() returns this variable
- the Hull::update() function takes a Pilot as a parameter, and creates the projectiles if Pilot.IsShoot()
- Merc creation involves making a FarShip, and a Guardian.
- the Guardian has a HullConfig
- the Farship has an AiPilot, and a HullConfig, as well as items and money
- HullConfigs do not appear to shoot things
- Hulls have GunMounts, life, ShieldFixtures, and HullConfigs
- Hulls are only ever built for SolShips
- FarShips have a function that builds and returns a SolShip called toObj, as part of the FarObj interface
- This is called in ObjectManager::update()- apparently, FarObjs are just stripped-down things to reduce load.
- When they get close, they convert to SolObjs, and back once they're offscreen. FarObjs delete themselves after a time delay. 
-After more inspection, it looks like the code asking mercs to shoot is good- I'll check the equip step next.

If anyone who is more familiar with the game notices something horribly wrong in there, please let me know :D .

**Comment by Cervator** [comment]
Thanks a lot for the research :-)

I've dug around in some of the related code you list. Will try to dig around some more, but am unsure I'll find the time before you'll have it all figured out, based on progress so far :D
