### ISSUE TITLE
Potential Enhancement: Larger ships provide larger cargo space

### ISSUE THREAD

**Issue by theotherjay** [MovingBlocks/DestinationSol#11]
***Moved: http://forum.terasology.org/threads/proposed-features-enhancements.1296/

**Comment by Cervator** [comment]
Hey @theotherjay - appreciate the bug reports and suggestions, but lets keep open ideas out of the issue tracker - they're too vague to track like this on GitHub :-)

This weekend we'll get properly started on Trello, which is much more apt for ideas as you can vote for them and better prioritize

Bugs are fine for GitHub, as are concrete things we *know* we are going to be working on in the near future. Ideas should go elsewhere.

**Comment by theotherjay** [comment]
I agree.  I'll move them once Trello is up.

**Comment by Cervator** [comment]
If you want to start making a big list of brief ideas you could post them in a big bulleted list in a new thread in the forum though: http://forum.terasology.org/forum/destination-sol.57 until we move them

Kinda like the backlog thread for Terasology

Or just wait a day or two. Probably Saturday sometime

**Comment by theotherjay** [comment]
Can I leave these for now?  I promise I'll move them!
