### ISSUE TITLE
Equipment refactoring (player, mercenaries ..)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#112]
Partly documenting some existing issues here plus kicking off a place to start redesigning a better equipment system.

We initially did a round of improvements to fix #55 which @askneller figured out so now the player's config data, stored in `prevShip.ini`, can sort of handle a concept of slots - a specific weapon can be tied to the 1st and 2nd weapon slots in the save (IIRC the same was prepared for armor and shield, but there's only one of each of those at present)

That in turned derailed how templates for ship config were set up and either broke mercenaries equipping weapons or it had previously been broken, but it was really awkward anyway (dropping a weapon in space and hoping you can get the merc to pick it up) - that has been mostly sorted out by now, just merged #110 by @JGelfand so mercenaries shoot again, huzzah!

That then leads us to where you again likely can't make a mercenary equip-on-drop, which could be fixed in the short term but you as the player still have very little to go on to cleanly manage all that. We could possibly fix it up to where mercs would equip a new weapon dropped on them if valid, but after a game restart I suspect they'd reset, which now in theory should let them get back to shooting with their default starting weapon.

We need a way to start both improving saves and the way you equip things. Some/most of that may be better off waiting until after #92 is finished, although that alone won't get us Terasology style saves - that also involves the entity system.

Maybe in the meantime we could do something simple to bridge us forward. What if we could add a button to the Items screen that much like changing the active page would change the active target? So if you had mercenaries you could switch from _your_ items screen to the mercenary's items screen. Then equip/unequip there would affect that one mercenary. To move items maybe new buttons "Move forward" and "Move back" which would transfer the item back and forward in the "chain" of available inventories?

At that point you'd still get a reset on game restart, but at least you'd have an easier way to move items around and picking what weapon a merc would use. You could even get the loot back your mercs so selfishly steal if you don't get it first! After #92 we could start looking at the concept of ship fitting a la EVE Online or something neato like that, as well as saving more than just the player's inventory between play sessions.

**Comment by JGelfand** [comment]
> What if we could add a button to the Items screen that much like changing the active page would change the active target?

I would prefer making mercs a valid talk target, and making talk bring up  a list of valid targets if there's more than one. Each merc's talk menu could contain "get" and "transfer" buttons, where the former gets items form the merc, and the latter transfers items to it. It could also contain an "equip" button that lets you equip the merc as you do from your own Items menu. The new-ish stuff to do here would be figuring out a good way to id mercs if you have identical ones, and a clean way of updating the list of talkable things.

**Comment by Cervator** [comment]
Talk target could work too, although it sounds trickier? If the standard talk distance would be involved (mercs have a tendency of not staying still, and waaay overcorrecting at times)

I expect this issue would be a temporary "doable right now" workaround until we completely overall gear to something more flexible and extensible, so am not aiming for perfection this round :-)

If you find a doable approach without too much work/hassle and want to do it then go for it! Progress is progress.

**Comment by Avalancs** [comment]
To distinguish between mercenaries, each one could get a random name from a pre-defined list. A classic example I'd like would be the phonetic alphabet https://en.wikipedia.org/wiki/NATO_phonetic_alphabet

To transfer items between player and a mercenary, maybe the buy/sell screens could be re-used with the mentioned talk option?

**Comment by Cervator** [comment]
@Avalancs yep that sounds fine :-)

We have a full-blown NameGenerator module in Terasology we could probably reuse here eventually, when we get more pieces of our Gestalt framework prepared. Placeholders would work well in the meantime.
