### ISSUE TITLE
Placement trouble with 3 star gates too close together

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#117]
Seems like a sort of extension to #56 - in this case the placement logic seems able to flip out if there are _three_ star gates too close together. Original report on [Google+](https://plus.google.com/u/0/102472991912179307006/posts/f5DHdUeQkzM) by saya orang:

```
Found a really rare glitch
If u start game near 3 warp gates
The warp gates will keep moveing, some dropped to planet, some stacked and teleporting gates XD
its pretty fun glitch btw>_<)﻿
```

Probably happens rarely enough to have hidden this long. May need to tweak at the solar system config to try replicating it.

**Comment by NicholasBatesNZ** [comment]
Closing as superseded by #299
