### ISSUE TITLE
Tiny bug: Music volume resets to max after restart

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#122]
Noticed as I set both volumes to "Low" but then on the next restart music was set to "Max" again. SFX volume was still correctly "Low"

Probably a simple bug in parsing (or initially setting) the option value.  I only see a `vol=0.33` in `settings.ini` - maybe the new entry for music just isn't being written yet?

There is also a slightly related code style issue that could be improved while we're at it: `MenuScreen.java` has methods `getVolName` and `getMusName` that are almost identical, yet don't use brackets the same. Easy quick thing to wrap properly and maybe clarify naming (`getVolumeName` - is that SFX or volume in general? And `getMusicName` I figure)

**Comment by Avalancs** [comment]
Yes, the GameOptions:save() function does not save the music volume. I'll do the fix and the refactor soonish.

**Comment by Cervator** [comment]
Closing as completed by #123!
