### ISSUE TITLE
Volume settings in main menu (not just in-game)

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#124]
Got to thinking about this when I had to go in-game to test volume settings. Maybe another one of interest to you @Avalancs :-)

Eventually we need to figure out nested settings screens, like in Terasology. Am not sure how much work that would be. Really the in-game and main menu could have Settings buttons that both go to the same sub-menu.

**Comment by Avalancs** [comment]
Yes, that sounds reasonable, especially since there could be more options in the future. I need to learn a bit more about the UI code, but making a new screen right now seems simple enough.

**Comment by Cervator** [comment]
Closing as complete :-)
