### ISSUE TITLE
Branch protection for develop

### ISSUE THREAD

**Issue by Rulasmur** [MovingBlocks/DestinationSol#133]
![image](https://cloud.githubusercontent.com/assets/14957173/23987007/e0172e4e-0a2f-11e7-8caa-5aa8f6d3edb5.png)

The idea behind this is that all code going into develop should always have at least one other pair of eyes take a look before it gets merged.

I believe this will help a lot with code quality in the future. And prevent any mess-ups and hopefully catch any obvious errors.

@Cervator @rzats Are you happy with the above settings?

**Comment by rzats** [comment]
LGTM! Though I think @Cervator does PR-less pushes every so often which would be blocked by _Protect this branch → Require pull request reviews before merging → Include administrators_, so I'd check his opinion before enforcing this setting.

**Comment by Rulasmur** [comment]
Spoke with @Cervator we will enable this Monday

**Comment by Rulasmur** [comment]
I have enabled this.
