### ISSUE TITLE
Saving does not work on Android

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#14]
Tried it out yesterday. No bombs for me on the next play session :-(

Probably should also change the "New Game" label to "Play Game" since the current approach actually hides the limited resume ability behind that button.

May be obsoleted by a more complete overhaul of save games.

**Comment by crazywolf132** [comment]
It would be a recent add then... if you take a look at my code that i have from a while back... it still all works. I would say that it is to do with the latest build you guys have made.

**Comment by crazywolf132** [comment]
@Cervator If you need anymore help on this... please contact me @ crazywolf132@gmail.com as i have all my latest code moved to http://gitpull.xyz/groups/SlyFoxStudios.

Or if you guys have fixed it and just forgot to close this issuse

**Comment by Cervator** [comment]
It may have worked in the past, I'm unaware if so. Pretty sure we still need a fix and/or more advanced saves eventually.

**Comment by Cervator** [comment]
Closing as out of date - I was able to resume a regular game on Android. Still need better saves, but not via this issue.
