### ISSUE TITLE
Maze tiles out of whack vs. their collision shapes

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#165]
At some point recently the maze tiles have gone out of sync with their collisions, meaning parts of solid tiles are penetrable and you can sometimes get stuck under maze walls.

Found while testing #164 but may be pre-existing. May also affect other things? But I bumped into plenty of asteroids and planets that seemed solid :-)

**Comment by vampcat** [comment]
Could you perhaps add a few screenshots?

It's possible - not likely, but possible - that you're confusing the maze background with the actual maze ( I've done that plenty :D )

**Comment by vampcat** [comment]
This was fixed sometime during gsoc :D
