### ISSUE TITLE
Game won't start on Linux (Optional.java)

### ISSUE THREAD

**Issue by AonoZan** [MovingBlocks/DestinationSol#173]
I have some issues starting game on my system.
https://pastebin.com/2DnU9VVC

**Comment by Malanius** [comment]
Hello,
could you please provide more info?
What version of Java are you using? What Linux distribution?

**Comment by Cervator** [comment]
And what version of the game - what did you download? :-)

**Comment by AonoZan** [comment]
Linux Acer 4.10.0-32-generic #36~16.04.1-Ubuntu SMP Wed Aug 9 09:19:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
And I tried to run v2.0 branch, as is pulled from github.

Run:

./gradlew run
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Configuration on demand is an incubating feature.
:main:compileJava UP-TO-DATE
:main:processResources UP-TO-DATE
:main:classes UP-TO-DATE
:main:jar
:desktop:compileJava
:desktop:processResources UP-TO-DATE
:desktop:classes
:desktop:run
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at org.destinationsol.game.sound.OggMusicManager.<init>(OggMusicManager.java:38)
        at org.destinationsol.SolApplication.create(SolApplication.java:81)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:143)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

> Building 87% > :desktop:run

And then there is crash report window.

**Comment by Malanius** [comment]
Thanks for the info.
I'm able to confirm this issue on v2.0.0 branch on both Ubuntu 16.04 and Windows 10.

Pondering into it, I've discovered that the v2.0.0 AssetHelper class is trying to find music inside "sounds" subfolder and as the Optional is not checked for isPresent(), it causes the error.

Fixing line 56 in AssetHelper class to actually search for music assets in "music" subfolder fixes this.

This is fixed on develop branch, as the AssetHelper has been replaced with newer Assets class along with getstalt and assets update.

I have a fix ready and I can open a PR, but I'm not sure how it goes for version branches.

**Comment by Malanius** [comment]
Pinging @Cervator and @vampcat for some insights how to deal with this...

**Comment by vampcat** [comment]
The v2 branch was specifically for the initial Gestalt experimenting - it was effectively throwaway. During GSoC, when we started putting my stuff into develop, it more or less became the new and real v2.0.0 .

So, the correct thing to do would be to rename v2.0.0 to v2Experimental or v2Android or something, and normal developers can just (are advised to) build upon develop.

**Comment by vampcat** [comment]
Also @AonoZan , your faction has already been merged into the "real" v2.0.0 (develop) in the form of Organic Module, so definitely check it out, if you haven't already :D

**Comment by Malanius** [comment]
Thanks for the info, if we rename it, should we at least keep it playable, if someone tries to run the game from that branch again?

**Comment by vampcat** [comment]
Closing, since it has been fixed in the v2.0.0 branch by #176.
