### ISSUE TITLE
Redo the Gooey ship, maybe in new hull directory structure?

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#18]
As a test of adding a new ship while DestSol was in my personal repo @PrivateAlpha added @GooeyHub as a ship. We might as well carry that work forward, maybe retest it in the new hull directory structure :-)

https://github.com/Cervator/DestinationSol/commits/master

After this is done I'll delete the old repo.

**Comment by SimonC4** [comment]
I created a guide in Steam on how to add a ship and used the Gooey ship from that repo as the example.
http://steamcommunity.com/sharedfiles/filedetails/?id=481833955

**Comment by Cervator** [comment]
Thanks! And agreed, my personal repo can finally go poof just to be replaced with a proper fork :-)
