### ISSUE TITLE
Ensure game hero is never null

### ISSUE THREAD

**Issue by eviltak** [MovingBlocks/DestinationSol#243]
## Problem

Currently, the game searches for the player ship on every update and, if found, a reference to it is assigned to `SolGame.hero`. However, if the hero is in the "transcendental" state (travelling through a StarPort) or no hero exists at all, `SolGame.hero` remains null. 

https://github.com/MovingBlocks/DestinationSol/blob/55d228c45fd94ed45393ec867df5d602a85ee2c6/engine/src/main/java/org/destinationsol/game/SolGame.java#L340-L350

This leads to a number of problems:

1. The player ship is searched for every frame, leading to suboptimal performance especially when a large number of `SolObject`s exist.
2. `SolGame.getHero` returns null when a null reference is not expected. A large chunk of the codebase - I daresay even the entire game - considers that a hero exists without fail. As such, NPEs may crop up here and there without explanation.
3. The `hero` should _never_ be null. As stated above, Destination Sol gameplay is wholly hero-centric; a player must therefore exist at all times. However, the code currently does not provide assurance that `getHero` will never return null (as evident from Slack discussions entailing the `Optional` refactor in #236).

## Proposed solution
Currently, a null `hero` has only two purposes:
- to signify that the hero is in the transcendental state or
- to allow for free camera movement without a hero for debugging.
https://github.com/MovingBlocks/DestinationSol/blob/55d228c45fd94ed45393ec867df5d602a85ee2c6/engine/src/main/java/org/destinationsol/game/SolCam.java#L66-L71

To work around this, the following can be done:
- `SolGame.hero` is set only once, on game load. `SolGame.transcendentalHero` is set only once, either on load or when the player enters the transcendental state for the first time.
- A boolean, `SolGame.isHeroTranscendental` is added to signify if the hero is in the transcendental state. If the value returned by the getter is true, callers should use `getTranscendentalHero` instead.
- Instead of checking for the non-existence of a hero, simply allow free camera movement if `DebugOptions.DIRECT_CAM_CONTROL` is true:
```java
public class SolCam {
    // ...
    public void update(SolGame game) {
        // ...
        float ts = game.getTimeStep();
        if (DebugOptions.DIRECT_CAM_CONTROL) {
            applyInput(game);
        }
        else {
            Vector2 heroPos = hero.getHull().getBody().getWorldCenter();
            // ...
        }
```

## Points to consider
- If the player ship `SolObject` is _recreated_ after it exits the transcendental state, the `SolGame.hero` becomes invalid. The reference must be updated every time the player ship is created.
- It might be worth exploring a separate `Player` object altogether, which persists for the entire duration of the game. All player ship (and other player-related stuff) creations/updates/state changes will be sent through the `Player` object, which manages the references internally.

**Comment by Adrijaned** [comment]
@eviltak Done, feel free to close

**Comment by vampcat** [comment]
Closing, as fixed by @246.

If you feel like something is still missing @eviltak, let me know and we can re-open this.

**Comment by eviltak** [comment]
@Adrijaned thanks for all the work! You might want to [close the issue in the PR itself](https://help.github.com/articles/closing-issues-using-keywords/) in the future :)

I think #246 has covered the points outlined in this issue, @vampcat. Thank you for closing the issue!
