### ISSUE TITLE
Mercenaries from previously saved session carry over to New Game session

### ISSUE THREAD

**Issue by manas96** [MovingBlocks/DestinationSol#251]
### What you were trying to do
I tried playing a New Game after saving a previous session in which I had hired mercenaries.
### What actually happened
The mercenaries I had hired in the previous session spawned with me in the New Game session.
### How to reproduce

* Step 1 Ensure there are no previous saves (i.e. the files, "mercenaries.json" and "prevShip.ini" should not be present in /engine/src/main/resources).
* Step 2 Launch the game and make a new game session. (Play Game -> New Game -> Ok). You might need to select Loaded Imperial Large ship to do Step 3 faster.
* Step 3 Visit a planet and hire a bunch of mercenaries.
* Step 4 Exit the game. This session's data will be saved.
* Step 5 Launch game again and start another New Game session. You will spawn with the previously hired mercenaries.

### Game version
Um.. I'm not sure about this. I downloaded the develop branch.

**Comment by vampcat** [comment]
Oooh, nice catch! Thanks for pointing it out :)
Would you like to try your hand at this, to get started with DestSol? :D

@Steampunkery I believe you're the culprit? :P

**Comment by Steampunkery** [comment]
Yeah I did that. I can fix it if you want, @manas96, or I can show you the files and stuff to get started if you want to fix it.

**Comment by manas96** [comment]
I fixed it. I've been having problems with my internet and git (my first time using git). I'll send in a pull request shortly.

**Comment by Steampunkery** [comment]
How exactly does the implementation of your fix work? I just want to make sure it lines up with some slated changes.
