### ISSUE TITLE
Ammo is not saved

### ISSUE THREAD

**Issue by oniatus** [MovingBlocks/DestinationSol#267]
When a game is loaded the player will always start with full ammo.
Steps to reproduce:
1. Start a new game with "Loaded Imperial Large" starting ship
2. Fire some rounds with left and right gun
3. (optional): Respawn: The player keeps the ammo
4. Exit to menu then continue the game, the player has full ammo again
Money on the other hand is saved.

**Comment by Steampunkery** [comment]
I can fix that. I'll get right on it.

**Comment by Steampunkery** [comment]
I stopped working on this because gestalt integration will serialize the object, thus saving the ammo. I can make a temporary fix though.

**Comment by Avalancs** [comment]
Tested on newest commit of develop branch, it has been fixed by https://github.com/MovingBlocks/DestinationSol/pull/318 so this issue can be closed.

**Comment by SimonC4** [comment]
Closing this issue as it is confirmed as fixed in version 2.0.0.
