### ISSUE TITLE
Velocity incorrectly labelled as speed in code

### ISSUE THREAD

**Issue by eviltak** [MovingBlocks/DestinationSol#290]
Throughout the code base, variables pertaining to an object's velocity have (incorrectly) been named `speed`, and those pertaining to an object's _speed_ (velocity magnitude) have been named `speedLen` and `speedScalar`. To avoid future terminology confusion, I suggest that we task ourselves with the renaming of such variables and parameters wherever they are used.

**Comment by Cervator** [comment]
I was curious if some of the many refactors and restylings might have caught this yet but - nope! Still 555 hits for "speed" in the code-base 😁 

Probably not all related to this, but still, looks like there's a ways to go.

**Comment by Malanius** [comment]
So, just to get sure:
- where `speed` is actually referring to `Vector2` object, it should be `velocity`, right?
- What about `speedLen`? Should it be just `speed` or `velocityLen`?
- `speedScalar` probably could be just `speed`, as speed is scalar by definition, but its bit confusing with `speedLen`

I hope I remember correctly, didn't deal with physics for a very long time, so any feedback on this will help.

**Comment by eviltak** [comment]
@Malanius Thank you for taking this issue under your wing! To answer your questions, both `speedLen` and `speedScalar` (and any other names  `speedXyz` where `Xyz` refers to the magnitude of the "speed" (velocity) vector) should be renamed to `speed`.  And yes, when a `Vector2` object is named `speed`, it should be renamed to `velocity`. Also, please keep in mind that declarations like `Vector2 targetSpeed` or `float targetSpeedLen` that have qualifying/describing prefixes and suffixes should also be refactored!
