### ISSUE TITLE
Asteroids not dropping loot

### ISSUE THREAD

**Issue by Adrijaned** [MovingBlocks/DestinationSol#305]
### What you were trying to do
Get money from asteroid
### What actually happened
Well, nothing
### How to reproduce

* Step 1 Launch game
* Step 2 Grab Imperial small, presumably even other ships
* Step 3 Shoot at rocks
* Step 4 Wait for nothing to happen

### Log details and game version
Latest develop
### Computer details
Arch linux

**Comment by Avalancs** [comment]
The root cause of the issue is a manual merge in 43fadbd793f68d14d4dff2d4f891db50118df9e0 in the Asteroid class which renamed the pos variable to position which is the same as the asteroid's position in the function throwLoot(). This made the loot's position to be thrown from the origin.
