### ISSUE TITLE
problem in playing the game

### ISSUE THREAD

**Issue by sohil1234** [MovingBlocks/DestinationSol#373]
when i click tutorial or play game the screen closes giving exit code 0.
and gives this error message:
java.lang.NullPointerException
	at org.destinationsol.assets.audio.OggMusicManager.playMusic(OggMusicManager.java:99)
	at org.destinationsol.SolApplication.play(SolApplication.java:228)
	at org.destinationsol.menu.NewShipScreen.updateCustom(NewShipScreen.java:82)
	at org.destinationsol.ui.SolInputManager.update(SolInputManager.java:220)
	at org.destinationsol.SolApplication.update(SolApplication.java:175)
	at org.destinationsol.SolApplication.safeUpdate(SolApplication.java:153)
	at org.destinationsol.SolApplication.render(SolApplication.java:132)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:120)

**Comment by sohil1234** [comment]
i am getting this message when i am typing command gradlew idea:
Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/4.10.2/userguide/command_line_interface.html#sec:command_line_warnings

**Comment by jellysnake** [comment]
Hey, in future please place log ouputs into hastebin.com or pastebin.com and link them instead, like how I edited your comment, because they are _really_ long.

As for the error, the errors about the gradle features being deprecated are benign and hence can be ignored.  
As for the main error, did you delete your copy of the game and then re-clone? Because the errors being thrown seem to indicate that there is some mismatch and you are not on the latest version for all of the code.

**Comment by sohil1234** [comment]
yes. can you tell me how to fix it

**Comment by arpitkamboj** [comment]
You just need to reclone the workspace. Check [this tutorial](https://github.com/MovingBlocks/DestinationSol/wiki/Full-Workspace-Setup) for more info.

**Comment by sohil1234** [comment]
i recloned the workspace as per the tutorial but still facing the same problem

**Comment by vampcat** [comment]
Hey sohil.

So, I just checked your account, and your develop and codein branches are waaaaay behind the current develop. You'll either have to delete your fork, and fork DS again - or you'll have to reset your develop to the latest upstream/develop. It would be way easier if you hopped onto IRC or Discord, and asked someone for help in reseting your develop to the latest version.

**Comment by BenjaminAmos** [comment]
I've run into this issue as well. The default music is never loaded if there is no music config file present in the module. To fix this temporarily, you can change the code in [OggMusicManager.java](https://github.com/MovingBlocks/DestinationSol/blob/c8879dfeaccbfd2dbb3d35af2c3e92265ddae106/engine/src/main/java/org/destinationsol/assets/audio/OggMusicManager.java#L161-L166) from this:
https://github.com/MovingBlocks/DestinationSol/blob/c8879dfeaccbfd2dbb3d35af2c3e92265ddae106/engine/src/main/java/org/destinationsol/assets/audio/OggMusicManager.java#L161-L166
to this:
```java
 try { 
     musicJson = Assets.getJson(moduleName + ":musicConfig"); 
 } catch (RuntimeException e) { 
     logger.warn("Music config not found for module " + moduleName + ":musicConfig"); 
     break; 
} 
```

(Change the return statement to a break one)

That fixed the issue for me. I have experienced it on a clean git clone as well (develop latest commit https://github.com/MovingBlocks/DestinationSol/commit/c8879dfeaccbfd2dbb3d35af2c3e92265ddae106), so it is a genuine issue.
This should be fixed when #374 is merged, although I have not tested it myself.

**Comment by sohil1234** [comment]
i deleted my fork and set up a new workspace and i am facing the same problem in the latest workspace

**Comment by sohil1234** [comment]
when i am playing the game my ship does not appear but it moves
 how to solve this problem(only my modules ship)

**Comment by sohil1234** [comment]
how to make a pull request for json schemas

**Comment by jellysnake** [comment]
@sohil1234 I'm closing this because the original problem has been solved. Additionally for questions like that you are better off [visiting our Discord](http://discord.gg/Terasology) (which you did)

**Comment by jellysnake** [comment]
@sohil1234 I'm closing this because the original problem has been solved. Additionally for questions like that you are better off [visiting our Discord](http://discord.gg/Terasology) (which you did)
