### ISSUE TITLE
Hired Merc Issue & map/damage issue

### ISSUE THREAD

**Issue by darkness7268** [MovingBlocks/DestinationSol#38]
It is very difficult to equip your hired ships. (I am only able to do this by dropping my items and hoping it picks it up.) If you could interact with it's inventory like you do while shopping (But without prices of course) that would fix that.

Another issue (I think, it may be intentional) You cannot take damage from collisions while viewing the map. To test this I headed straight towards an asteroid belt and then viewed my map. once I heard the impact noise I got out of the map and had no damage where I should have taken about 7.

Signature:
I am not a person who knows how to code but I am rather swift in finding bugs in games. I will continue to look for bugs in future releases. To contact me via email(Since I don't check my account messages) @ scot.britton@yahoo.com

**Comment by Cervator** [comment]
Thanks for the report :-)

This is more of an enhancement request but yeah we know mercenaries are very difficult to use currently, pretty close to bug territory. Definitely needs work.

The map issue I haven't tried, that might be a bug.

**Comment by darkness7268** [comment]
I have re-tested the map issue. It turns out that Since I'm not taking much damage from a collision and since im technically in a state where I heal if i have the repair kit, I heal before I can see that I took damage. So I tried this without a repair kit and I do in fact take damage while doing what I stated earlier.

**Comment by Cervator** [comment]
Ahh. Alrighty then. Appreciate you following up on it!
