### ISSUE TITLE
Mercenaries spawn as hostile to the player

### ISSUE THREAD

**Issue by IsaacLic** [MovingBlocks/DestinationSol#410]
### What you were trying to do
I purchased some mercenaries at one of the planets, intending to try to test bug #354. I assumed that the mercenaries would follow and support me.

### What actually happened
The mercenaries spawned as hostile ships, and so the trade base killed them while they were attacking me. They were listed in the mercenaries UI screen despite the change in faction.

### How to reproduce

* Start a new Game
* Go to a planet and recruit a few mercenaries
* The mercenaries will spawn as enemy ships and will attack

### Log details and game version
most recent in the "develop" branch (a0eda93)

**Comment by Cervator** [comment]
Fixed by #412 whenever it gets tested out and merged :-)

**Comment by Avalancs** [comment]
#412 has been merged, and I also tested on 4a5142c5a35c5efaa18e2dda76dd1c400786a9c9 and it works fine. This ticket can be closed.
