### ISSUE TITLE
Unauthorized error getting libs

### ISSUE THREAD

**Issue by jsykes** [MovingBlocks/DestinationSol#421]
### What you were trying to do
Install dependencies

### What actually happened
Unauthorized Error

### How to reproduce

* Run ./gradlew run

### Log details and game version
Master branch

### Computer details
OSX Mojave

**Comment by Adrijaned** [comment]
Hi, would you be able to pop into our chat to get this sorted out? It's on discord.gg/Terasology, and we will be more probably able to help you there, or  #destination-sol on freenode (or #terasology if no one answers in the first room) - both those chat platforms are bridged across, choose whichever you wish. Anyway, cerv may still reach out to you there to get you sorted out even this way

**Comment by Cervator** [comment]
Hi @jsykes - could you be a bit more specific on the unauthorized error please? Paste in a stacktrace or something? Hard to investigate since our Artifactory seems to be up and available normally (occasionally it is not and can trigger this sort of issue)

Also: you might want to try the `develop` branch instead of `master` :-) We're closing in on finishing the v2 release in the `develop` branch but `master` hasn't updated for 2+ years

**Comment by jsykes** [comment]
Hello! Here is the error I get when I try to build, generate for idea, or sync gradle.


**A problem occurred evaluating project ':desktop'.
> Could not resolve all files for configuration ':desktop:runtime'.
   > Could not download org.everit.json.schema.jar (com.github.everit-org.json-schema:org.everit.json.schema:1.9.2)
      > Could not get resource 'http://artifactory.terasology.org/artifactory/virtual-repo-live/com/github/everit-org/json-schema/org.everit.json.schema/1.9.2/org.everit.json.schema-1.9.2.jar'.
         > Could not GET 'http://artifactory.terasology.org/artifactory/virtual-repo-live/com/github/everit-org/json-schema/org.everit.json.schema/1.9.2/org.everit.json.schema-1.9.2.jar'. Received status code 401 from server: Unauthorized
**

**Comment by jsykes** [comment]
Also, I was wrong earlier. I'm on the develop branch

**Comment by Cervator** [comment]
Thanks! That's helpful :-)

I get auth prompts as well just trying those links, but then I've seen that from time to time as an oddity, can't recall if I figured out why.

I was able to freshly clone and `gradlew idea` myself just fine, and Artifactory browses OK. However it _did_ show really high memory usage, so perhaps it was unstable. After restart it went from 90% memory usage to 30% usage :-)

Could you try again now and see if that helped? If not is there anything at all odd about your internet connection, such as being on a filtered university campus network or something of the sort?

**Comment by jsykes** [comment]
Hi, no unique filtered network here. I even disabled my network pihole temporarily to see if that changed anything. If it worked for you, I'm thinking you have a cached version of the lib on your machine already so it didn't bother getting it?

**Comment by Cervator** [comment]
Possibly, and @pollend just hit it as well, for a different project under our little umbrella.

Closest idea I have is that the order the repositories are resolving in is off somehow - either something upstream is unavailable so resolution falls through to our repo which is just a proxy for artifacts like that json lib (or the logging lib @pollend) is failing on) or something caused an unexpected change in our Artifactory itself. Which would be weird as it hasn't really changed in years :/

This issue does seem to pop up with some irregularly. But either it self-resolves (something upstream gets fixed?) or the person gives up - I don't think we've found any more exact details for the problem. It would be very lovely to figure it out!

**Comment by jsykes** [comment]
Well it seems like 1.9.2 isn't able to resolve for some reason. I think it tries to pull it from Github but then it tries your repos last.

Changing the version to 1.11 at least got it working for me and it was able to find that. Maybe this is the fix?

compile "com.github.everit-org.json-schema:org.everit.json.schema:1.11.1"

**Comment by NicholasBatesNZ** [comment]
Fixed! Thank you for reporting and also for the solution @jsykes :)
