### ISSUE TITLE
Include in F-Droid

### ISSUE THREAD

**Issue by UnderSampled** [MovingBlocks/DestinationSol#425]
Destination Sol app seems to be eligible for inclusion into The F-Droid Android FOSS app repository. Assuming there are no non-free libraries and the build system is sufficiently automated, this should require little effort on this project's part. If you would like to support F-Droid and give people a better experience, you can add screenshots and descriptions to a 'metadata' folder in your repository (Instructions [here](https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/#in-the-apps-source-repository)). If you would prefer not to be included, please let us know.

**Comment by BenjaminAmos** [comment]
I've submitted https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10609 for this and plan to investigate fastlane metadata for the DestSolAndroid repository next, likely in conjunction with finishing MovingBlocks/DestSolAndroid#6.

**Comment by Cervator** [comment]
Fastlane automation now works! 🎉

**Comment by BenjaminAmos** [comment]
As an update, https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10609 has been merged. Assuming no further issues hopefully the game should make its way onto the store soon. I'll close this issue when that happens.

**Comment by BenjaminAmos** [comment]
The game is now available at https://f-droid.org/packages/com.miloshpetrov.sol2.android/, so I'm going to close this issue for now. Feel free to reply if that version gets out-of-date or isn't appearing for you.

**Comment by Korb** [comment]
> You can download the game on Steam, get it in the Google Play Store, or download the very latest version from our build server (warning: latest build may be unstable)

@BenjaminAmos, please add a [link to F-Droid](https://f-droid.org/en/packages/com.miloshpetrov.sol2.android/) in `README.md`.
