### ISSUE TITLE
Crash on Android with hull restructure

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#47]
At least I figure it is from the big merge as this is the first time I've tried to test

![screenshot_2015-07-12-00-07-25](https://cloud.githubusercontent.com/assets/1063833/8636344/92775166-282a-11e5-9a1e-8dfd737dc600.png)

**Comment by SimonC4** [comment]
Did you do the manual step of copying the res directory into the assets directory in the android folder? I had the same error, but forgot that step and after that it worked as expected.

**Comment by Cervator** [comment]
Hehe, I did have res under assets. However, I had the *old* res under assets :-)

Thanks for the reminder! All is well
