### ISSUE TITLE
Update Steam Cloud Settings for v2.0.0

### ISSUE THREAD

**Issue by SimonC4** [MovingBlocks/DestinationSol#476]
The current status of the Steam Cloud settings are to save only a single file: prevShip.ini. Running v2.0.0 I noticed that there are additional files that are saved, so these should be added to the Steam Cloud settings in preparation for the v2 release. 

### Current Settings
Byte Quote Per User: 1000
Number of Files Per User: 1
List of files:
* prevShip.ini

### Proposed Settings
Byte Quote Per User: ~5000~ 1000000 (1 MB)
Number of Files Per User: 3
List of files:
* prevShip.ini
* mercenaries.json
* world.json

### Notes
settings.ini isn't included as that contains device specific settings.

**Comment by SimonC4** [comment]
I think I've covered all the files. I'm not sure how large they can possibly be though, so have taken a guess at 5 KB. Let me know if this needs to be bigger or if any other files should be included.

**Comment by NicholasBatesNZ** [comment]
I just started as Syndicate Capital and bought myself a bunch of mercenaries, proceeded to crush a number of them, picking up their items. I got the files up to 3.8kb total and that was after just a minute or so of playing (albeit with a rather OP ship) so I don't think that 5kb will cut it unfortunately.

**Comment by SimonC4** [comment]
I had another read through the Steam documentation and I don't think there's much of an issue changing that limit. The only mention is "It's recommended to set the values to reasonable amounts for your game title."

I've increased the proposed limit to 1 MB which I'm assuming should be ample.

**Comment by SimonC4** [comment]
Updated the Steam Cloud settings in Steam and have published these changes.
