### ISSUE TITLE
Mouse Issues on Windows 8.1 in Fullscreen Mode

### ISSUE THREAD

**Issue by SimonC4** [MovingBlocks/DestinationSol#48]
Reported on Steam: http://steamcommunity.com/app/342980/discussions/0/530647080132784507/

OS: Windows 8.1 64-bit
Resolution: 1920 x 1080 (was also trying to play the game at 1920 x 1080 resolution.)

I've downloaded the game and had just selected fullscreen now the mouse jumps all over the place. I am unable to hover the mouse over any buttons because it blinks around. BTW it's still in window mode even after I chose the fullscreen option.

**Comment by Cervator** [comment]
Good news! I can reproduce on my tablet running Win 8.1 :-)

... now what, hmm! Would need some time to actually look at code, just squeezed in some testing real quick.

For my exact steps

* Ran game (nice and fresh, didn't even have Steam installed on tablet before)
* Got standard res (800x600 IIRC, which was also lowest supported), windowed, menu was fine, no jumping
* Changed to fullscreen under resolution - screen flashed but the window didn't seem to really resize, just stuck to the top left with the normal desktop + windows visible in the background, obviously at a different resolution than before (probably an aspect ratio thing?)
* Got the jumpy mouse when highlighting buttons.
* Went back to resolution and picked 1920x1080 (closer to or matching the natural aspect ratio of the tablet) - no issues in menu!
* Entered the actual game, mouse went real weird again, usually sticking to the sides, acting like it was drunk, very sluggish and exaggerated motion
* Made it back to menu, still same effect active on the cursor
* Switched to 2160x1440 or so, the native resolution - same effect
* Restarted game - *fully functional* ! Even in-game
* Went back to main menu - got sluggish cursor again (still no blinking though)

So I would say there could be 2-3 issues in fullscreen

* If the aspect ratio is off the cursor can get warpy - trying to adjust poorly?
* If resolution is less than native you can get a boxed pseudo-fullscreen
* Something can make the mouse cursor drunk. It feels like an input buffering issue. Takes a lot of convincing to even go in the right direction, as if the game is still trying to go through remaining moves in a buffer before it accepts the newer input (might move right a bit, then try to move left, but the cursor keeps going right for a while before finally going left again)

Possibly me using a touchpad (Surface Pro 3) could be making the third issue worse, or entirely cause it... or maybe not, connected a USB mouse and same issue (just a slight bit more control to make tinier moves)

**Comment by Cervator** [comment]
Mac issue reporting mouse issue as well: http://steamcommunity.com/app/342980/discussions/1/535150948597573921/

Not trying to necessarily cram that onto this Windows issue but we should probably recheck that after we figure this one out :-)

**Comment by SimonC4** [comment]
@Cervator, might be a long shot but do you want to try using the latest updates to version 2 of lwjgl and see if you still get the same issue. I see in the commit history there are some changes around mouse tracking: https://github.com/LWJGL/lwjgl/commits/master

To get the latest version, go to http://ci.newdawnsoftware.com/job/LWJGL-git-dist/lastBuild/ for the nightly builds and download the lwjgl-maven-2.9.4.zip file. Inside the file are these jar files that we use:
lwjgl-platform-natives-windows.jar
lwjgl.jar
lwjgl_util.jar

**Comment by Cervator** [comment]
Cautious optimism!

I grabbed the latest DestSol build from Jenkins. Downloaded the 2.9.4 zip and spliced the right files into the game download. Still got the funny fullscreen issue when not at native resolution (that part I imagine we could fix with better handling of fullscreen somehow) but I did not get any of the other issues (drunk cursor)

Not 100% certain I'm replicating correctly but it seems like it would be worth pursuing the upgrade. We could always make our own wrapped LibGDX with the latest LWJGL and publish it to our Artifactory for usage, if LibGDX itself isn't pulling in LWJGL 2.9.4 :-)

**Comment by SimonC4** [comment]
@Cervator can you try out my branch on your Windows 8.1 device. I'm changing the way the mouse cursor is loaded and may have discovered a fix for this issue. The current commit, https://github.com/SimonC4/DestinationSol/commit/88a2a66b38837cdc3a63032cfb80cb5c78e214a7, replaces the current mouse cursor as well as using the existing method, so you essentially have two mouse cursors. This has the unintended benefit of showing the difference between the two. 

I've managed to recreate a scenario on my Linux VM where the old cursor would be very laggy and could take a second or two to catch up. I suspect this is a similar issue to what you are having so would be good to confirm it.

**Comment by Cervator** [comment]
Interesting. Cloned fresh on tablet and grabbed your branch.

The "drunk" cursor is entirely gone. In the resolution I started at I only had one cursor after switching to fullscreen. But then increasing the resolution got me to where I'd get two, so maybe it only activates at that point or only affects some resolutions? 1280x1024 on my tablet gets it, native resolution is 

In any case the interesting part: In the menu the "smaller" cursor (for me it was more too the left of a larger cursor) was accurate vs the menu buttons. But in-game the "larger" cursor (more to the right) was what the ship would point at.

The more I moved to the left the closer the two cursors would get, overlapping at the left edge. The bigger cursor more to the right would stop at the right edge leaving the smaller cursor further back to the left and unable to make it to the right edge

Exited the game, loaded again. Single cursor, even in-game. Went to resolution and used 1024x768. This time the cursors showed subtly different behavior where the slightly smaller one seemingly was falling behind but trying to catch up. This time for whatever reason the smaller one was a bit to the right, more matched with the bigger on the left edge again, and entirely off-screen on the right side (with the larger cursor on the left now still determining the edge on the right). Smaller cursor still was what would highlight the buttons.

Hope that helps! :-)

**Comment by Cervator** [comment]
Speaking of - two new related user reports: http://steamcommunity.com/app/342980/discussions/1/535151589908633094/

Key note: Differing behavior if launched via Steam or not. I got the "drunk" cursor earlier from a Steam launch, today I tested running from source.

**Comment by SimonC4** [comment]
I've created another issue, #61, as I'm certain this is a separate issue to the drunk cursor effect.

**Comment by SimonC4** [comment]
I'm not sure my mouse-improvements branch is going to be a fix for this. I've just seen that there is a known issue https://github.com/libgdx/libgdx/pull/2841 where the game can crash after changing the mouse cursor repeatedly.

It also looks like it doesn't work at all on my linux machine. @grauerkoala, can you try the branch out on your linux setup to confirm. https://github.com/SimonC4/DestinationSol/tree/mouse-improvements the issues I'm seeing are that the mouse cursor doesn't change on linux until you move the mouse and then it reverts back to the default image almost immediately.

@Cervator, might be worth checking what your experience is on Windows 8.1 again, now that #61 is fixed. Just to confirm that this is still happening and if the symptoms are the same.

**Comment by Cervator** [comment]
Sure, I'll try to play with it tomorrow. Got home very late today.

I made a separate issue for the boxed fullscreen just now as I don't think we've tried dealing with that, that way we can focus on just cursor issues here.

**Comment by Cervator** [comment]
The game behaves very well on my Win 8.1 tablet at this point. Tested both from source and via Steam beta. I have to work pretty hard at even spotting the flickering cursor when in a resolution that doesn't match the native aspect ratio, I'm not actually sure I can anymore.

... is this issue actually fixed by now? With the "windowed" fullscreen split out, that is :-)

The LibGDX issue is a blocker for your alternative fix, which may help with the flickering, right? Maybe there are still some systems where the flickering is still severe. Or we may not need it.

I'm sure we can dig up more mouse issues if we go looking, like the mouse-trapped-in-window bit. But we seemingly might be able to close this as complete, add it to the v1.3.0 changelog, and release. What do you think?

Let me know and if OK I can merge to master tomorrow morning and we can formally release.

**Comment by Cervator** [comment]
Closing as sufficiently resolved after some brief discussion on IRC and with enough issues split out to fix later :-)

**Comment by grauerkoala** [comment]
> It also looks like it doesn't work at all on my linux machine. @grauerkoala, can you try the branch out on your linux setup to confirm.

> Closing as sufficiently resolved after some brief discussion on IRC and with enough issues split out to fix later :-)

Apologies for the delay! Mouse positioning now works well on my Linux machine. As far as I can tell, that issue is fixed.

**Comment by Cervator** [comment]
Huzzah! :-)

I posted the little new faction write-up, in case you're still interested in doing a faction too: http://forum.terasology.org/threads/dark-empire-arc-first-major-new-content-piece.1355 - probably some of the prepwork would help with adding any new factions (or more advanced things like standings)
