### ISSUE TITLE
Options Menu Shouldn't Be Visible on Android

### ISSUE THREAD

**Issue by SimonC4** [MovingBlocks/DestinationSol#490]
### Description
The Options menu is visible on the Android build and shows settings that aren't applicable, such as changing resolution and input. Previously this menu had been hidden on Android, but there are additional items that may be useful to change on Android, e.g. map scroll speed.

### Log details and game version
version 2.0.0

### Computer details
Android Emulator - API 28

**Comment by BenjaminAmos** [comment]
I wrote some code a while ago that hid some of the menu options on Android. You can find it at https://github.com/BenjaminAmos/DestinationSol/commit/0a2a9967740247e105f7dcf0a9e978a9a1dd37c5. I've just rebased it to include the map scroll speed option as well. You might be able to make some use of it.
![DestinationSolOptionsMenu](https://user-images.githubusercontent.com/24301287/74927588-cf54d380-53cf-11ea-9dd5-262fb99cbc68.png)
