### ISSUE TITLE
Bug - No ship icon in map screen while in hyper jump

### ISSUE THREAD

**Issue by theotherjay** [MovingBlocks/DestinationSol#5]
There is no ship icon for the player's ship, while in the map screen, while in a hyper jump between gates.  At first this didn't seem like a big deal, but it started to get annoying not being able to see *exactly* where I'm at while travelling.

**Comment by darkness7268** [comment]
I would also like to add that while using the hyper jump you can't see the enemy ships 'cation' icon that marks if an enemy is too dangerous for you.

**Comment by Viech** [comment]
Also, enemies are shown blue like allies to me during hyperjump.

**Comment by Cervator** [comment]
Closing as fixed by #89 

I figure the behavior of blue (unable to hurt you) and no caution is OK for now, but good observations none the less :-)
