### ISSUE TITLE
beta v2.0.0 - Ship not pointing at a crosshair when on a planet

### ISSUE THREAD

**Issue by simplyshnimply** [MovingBlocks/DestinationSol#510]
Greetings.
So, there's a weird bug I found while playing on a new v2.0.0 beta of Destination Sol:
When I land at a planet, my ship stops pointing where crosshair at and starts pointing some other way, and where it's pointing changes as I fly around the planet, for example: when I'm at one side of the planet - my ship points towards the left of a crosshair, and when I move to the other side, it points to the right. As I move around the planet, it shifts all around, including one spot where it points correctly at the crosshair like it should. I only have this bug while I'm on the planet; it fixes as soon as I'm in space. It's kinda annoying, but still playable.

I use Linux Mint. 
Here's also few screenshots on different sides of the planet, where ship SHOULD be pointing at the crosshair, but it isn't.

![20200427182335_1](https://user-images.githubusercontent.com/64425192/80391954-25a22f00-88b7-11ea-9993-d72d13297027.jpg)

![20200427182351_1](https://user-images.githubusercontent.com/64425192/80392014-3f437680-88b7-11ea-8e3b-3058ed8d082b.jpg)

![20200427182244_1](https://user-images.githubusercontent.com/64425192/80391825-eecc1900-88b6-11ea-9ff6-4e9bf9e5d98e.jpg)

And normal position in space:

![20200427184100_1](https://user-images.githubusercontent.com/64425192/80391887-07d4ca00-88b7-11ea-8c9c-2f8e948e2efd.jpg)

**Comment by NicholasBatesNZ** [comment]
Seems to have been introduced in #499 :eyes:

**Comment by Cervator** [comment]
Fixed now 👍
