### ISSUE TITLE
The Body class needs a bridge to work with ECS architecture

### ISSUE THREAD

**Issue by IsaacLic** [MovingBlocks/DestinationSol#521]
LibGDX’s `Body` class, which handles the physics, isn’t one of the allowable data types for a component, which would be problematic for serialization. It also contains a mix of information and logic, which goes against the separation between components and Systems. It can’t just be redesigned, though - it's part of the LibGDX structure, and it's the main way that the physics engine interacts with objects. This is the biggest obstacle for my work right now. In order to continue with the project, I need a way to associate an entity with a `Body`.

**Comment by NicholasBatesNZ** [comment]
#527
