### ISSUE TITLE
After respawning, the wrong weapons are selected

### ISSUE THREAD

**Issue by grauerkoala** [MovingBlocks/DestinationSol#55]
I noticed that after respawning, both by restarting the game and by simply hitting "respawn" in the game menu, instead of the weapons I had used previously, the first two matching weapons in my inventory where equipped. I'm assuming that is unintended behaviour and I'll take a look.
I've only noticed this behaviour with the Hunter yet, but I'm reasonably sure that I never had the conditions described above present when I was using other ships. I will investigate further.

**Comment by askneller** [comment]
Hi guys. I was looking into this and according to the following code the <strong>best</strong> weapons, armor, and shields are equipped when the ship is created/respawned. Do you want this changed to the previously equipped items or left as is?

    if (i instanceof GunItem) {
        GunItem gNew = (GunItem) i;
        if (gunIsBetter(gNew, g1, ic, m1)) {
          ship.maybeEquip(game, gNew, false, true);
          g1 = gNew;
        } else if (m2 != null && gunIsBetter(gNew, g2, ic, m2)) {
          ship.maybeEquip(game, gNew, true, true);
          g2 = gNew;
        }
      } else if (i instanceof Armor) {
        Armor aNew = (Armor) i;
        if (a == null || a.getPerc() < aNew.getPerc()) {
          ship.maybeEquip(game, aNew, true);
          a = aNew;
        }
      } else if (i instanceof Shield) {
        Shield sNew = (Shield) i;
        if (s == null || s.getLife() < sNew.getLife()) {
          ship.maybeEquip(game, sNew, true);
          s = sNew;
        }
      }

**Comment by Rulasmur** [comment]
It would be best if it respawns with the previously equipped items

**Comment by Cervator** [comment]
Yeah I think that's better too for a future in which it may be harder to even determine if a weapon is better or not :-)

**Comment by SimonC4** [comment]
I agree with @Rulasmur and @Cervator, previously equipped items would be better.

**Comment by askneller** [comment]
Ok, I'll get on it.

**Comment by Cervator** [comment]
Closing as complete!
