### ISSUE TITLE
Crash on startup - Windows 10

### ISSUE THREAD

**Issue by Thalgrumm** [MovingBlocks/DestinationSol#554]
Downloaded the game through Steam, but when trying to run the game, the new logo pops up but is replaced by the crash reporter.  Crash reporter says a fatal error occurred GdxRuntimeException: Couldn't create window, and spits out this error text:

com.badlogic.gdx.utils.GdxRuntimeException: Couldn't create window
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:445)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:391)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:379)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:108)
	at org.destinationsol.desktop.SolDesktop.main(SolDesktop.java:149)

I have tried opening the game 4 times and every crash report is exactly the same. However, this may be a graphics library or driver issue as multiple versions of minecraft also crash on launch, stating that "Minecraft was unable to start because it failed to find an accelerated OpenGL mode." So, if its a DS thing, it needs fixing, but if its a problem with my computer, any help would be greatly appreciated.

Running on a Sony Vaio PCG-61A14L, Intel Core i5-2450M, 6GB DDR3 RAM, with 64-bit Windows 10.

**Comment by Cervator** [comment]
Hi there @Thalgrumm  - sadly it is about 99% certain to be about your computer's hardware, especially if Minecraft crashes as well. Both use the same Java libraries and OpenGL for graphics. Very rarely we see a system where upgrading your video card drivers help, or find out that the user has _both_ a low-end graphics chip as well as a dedicated GPU and for some reason the OS is trying to launch the game on the weaker graphics. But it sounds like that laptop is from 2011 so odds are it just won't work :-(

**Comment by Thalgrumm** [comment]
Aww, that sucks, maybe another time with another computer. Thanks for the info.

**Comment by Graviton48** [comment]
@Thalgrumm, please close the issue if resolved, thanks :D
