### ISSUE TITLE
Textures load improperly (Android)

### ISSUE THREAD

**Issue by Esnardo** [MovingBlocks/DestinationSol#558]
Issue: Textures are completely shuffled when exiting the game with the back button. Often you take on the appearance of an enemy ship that was nearby when you exited, and I was saw an item sprite be replaced with the desert planet turret's "edge of screen" icon. 

Repro:
1. On android, exit the game using the back button.
2. Reopen the game and reload your save (untested with new game)
3. Look at yourself, or nearby ships, or asteroids, or about 20% of things.

V2.0.0

LGK20, Android

**Comment by NicholasBatesNZ** [comment]
Seems like this could be related to https://github.com/MovingBlocks/DestSolAndroid/issues/9
