### ISSUE TITLE
Map culling doesn't respect pan 

### ISSUE THREAD

**Issue by Esnardo** [MovingBlocks/DestinationSol#564]
Issue: Map culling doesn't work properly if you pan the camera. Things that are on screen get culled out if the game thinks they aren't on screen.

Repro:
1. Go to map
2. Zoom in
3. Pan to something that should have icons, like the travelling hunters, or starports
4. On second thought, this could actually be a symptom of #557 

V2.0.0

LGK20, Android

**Comment by Graviton48** [comment]
Same on Windows desktop, v2.0.1
