### ISSUE TITLE
Bad collision boxes for maze

### ISSUE THREAD

**Issue by Graviton48** [MovingBlocks/DestinationSol#576]
### What you were trying to do

trying to go inside a maze

### What actually happened

noticed weird collision boxes implemented for the maze

### How to reproduce

*go to the maze at the bottom of the system you start in
* try to enter the maze
* notice weird collision boxes

### Log details and game version
Windows PC
v2.0.1

### Computer details
i3 3220
gtx 1050
8gb ram

**Comment by BenjaminAmos** [comment]
This doesn't appear to be an issue with the maze collision boxes themselves. In the Box2D editor the maze parts appear fine. I think that the collision shapes are being loaded incorrectly in-game.

You can view the collision shapes by setting the `drawPhysicBorders` value to `true` in `engine/src/main/resources/debugOptions.ini`.

![image](https://user-images.githubusercontent.com/24301287/151659578-d9eda901-1f08-4cfa-9eba-3f7682ea13de.png)
![image](https://user-images.githubusercontent.com/24301287/151659545-79f318e9-7888-46d2-923d-9dc8e248e22e.png)
