### ISSUE TITLE
"Shard" texture names should be renamed to "Rubble"

### ISSUE THREAD

**Issue by IsaacLic** [MovingBlocks/DestinationSol#582]
In #550, `Shard` was renamed `Rubble`. There are some textures that still are named `Shard_X` which should be renamed, and the associated code that pulls the texture from the files should be refactored.

**Comment by Mystic-Slice** [comment]
Hi, Is this still open? If so, I would like to work on it.

**Comment by Cervator** [comment]
Completed by #611
