### ISSUE TITLE
Minor follow-ups to PR #604

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#606]
Three meaningful review comments were left unresolved - would be nice to get them addressed by @IsaiahBlanks :-)

**Comment by IsaiahBlanks** [comment]
Those comments were addressed in the following commit from PR #607: https://github.com/MovingBlocks/DestinationSol/pull/607/commits/aa2af0a539634bcfb7ab7db2753425a8bf9ba1f0

**Comment by Cervator** [comment]
Cool, closing, thanks 👍
