### ISSUE TITLE
Mouse Off Centre After Changing Resolution

### ISSUE THREAD

**Issue by SimonC4** [MovingBlocks/DestinationSol#61]
I'm fairly certain these is the issue reported on Steam: http://steamcommunity.com/app/342980/discussions/1/535151589908633094/

Steps to reproduce
1. Start the game with the settings that have: resolution 800 x 600, windowed, and with mouse control. These are the default settings.
2. Change resolution to 1366 x 768 (or similar widescreen aspect ratio)
3. Start a new game
4. Move the mouse pointer to the right of the ship

Expected result:
The ship turns to the right

Actual result:
The ship doesn't turn to the right until the mouse is very far to the right.

**Comment by SimonC4** [comment]
Fixed in #62.

**Comment by Cervator** [comment]
Ah, hadn't noticed this didn't auto-close. I think it would have with a commit message like "Fixes #61" - the "issue" is probably throwing off GitHub's detection.
