### ISSUE TITLE
Opening map causes camera to zoom out

### ISSUE THREAD

**Issue by Sceptres** [MovingBlocks/DestinationSol#627]
### What you were trying to do
Move the hero and while moving, opening the map, and then return to the game to continue playing after checking the map.

### What actually happened
After opening the map while moving then closing it, everything in the game became smaller (the hero, asteroids, enemy ships, etc.).

### How to reproduce

* Start moving your hero in any direction
* While moving open the map
* After viewing the map, close it. Everything in the game will have shrunk down to a smaller size than before

### Log details and game version
Game version: v2.0.0

### Computer details
CPU: i7-1165G7
RAM: 16 GB
GPU: Intel Iris Xe

**Comment by Sceptres** [comment]
I think solving issue #614 would help so that the view does not keep zooming out while the map is open. That is if we stop the ship from accelerating while the map is open

**Comment by Cervator** [comment]
> I think solving issue #614 would help so that the view does not keep zooming out while the map is open. That is if we stop the ship from accelerating while the map is open

That sounds reasonable yes - if the player _starts_ accelerating then opens the map, pause acceleration / turning as if no keys are being hit, and let the rest of the game act accordingly 👍
