### ISSUE TITLE
No sound at all

### ISSUE THREAD

**Issue by jozefcifre** [MovingBlocks/DestinationSol#694]
### What you were trying to do

I was trying to run DS develop.

### What actually happened

No music, no teleporting sound effects, no firing sound, no sound at all.

### Game version

develop

### Log details

[Configuration on demand.txt](https://github.com/MovingBlocks/DestinationSol/files/13289055/Configuration.on.demand.txt)

### Operating System

Linux

**Comment by BenjaminAmos** [comment]
Is this NixOS again?

> AL lib: (EE) ALCplaybackOSS_open: Could not open /dev/dsp: No such file or directory

I suspect that this line might have something to do with it. libGDX uses LWJGL 3 for rendering and audio, which in turn wraps OpenAL. Something is going wrong with OpenAL here.

**Comment by BenjaminAmos** [comment]
Could you set the environment variable `ALSOFT_LOGLEVEL=3` and then attach the logs from running the game again here? Running `export ALSOFT_LOGLEVEL=3` before `./gradlew game` should work.

Assuming it is NixOS, this is completely untested but maybe also give this a try (I added pulseaudio - same instructions as https://github.com/MovingBlocks/DestinationSol/issues/693#issuecomment-1784090234):

```nix
let
  nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-23.05";
  pkgs = import nixpkgs { config = {}; overlays = []; };
in

pkgs.mkShell {
  packages = with pkgs; [
    git
    temurin-bin-11
    libglvnd
    libpulseaudio
  ];

  LD_LIBRARY_PATH = "${pkgs.stdenv.cc.cc.lib}/lib:${pkgs.libglvnd}/lib:${pkgs.libpulseaudio}/lib";
}
```

**Comment by jozefcifre** [comment]
Yeah, it's NixOS unstable.

[alsoft-logs.txt](https://github.com/MovingBlocks/DestinationSol/files/13290333/alsoft-logs.txt)

**Comment by jozefcifre** [comment]
> Assuming it is NixOS, this is completely untested but maybe also give this a try (I added pulseaudio - same instructions as [#693 (comment)](https://github.com/MovingBlocks/DestinationSol/issues/693#issuecomment-1784090234)):
> 
> ```nix
> let
>   nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-23.05";
>   pkgs = import nixpkgs { config = {}; overlays = []; };
> in
> 
> pkgs.mkShell {
>   packages = with pkgs; [
>     git
>     temurin-bin-11
>     libglvnd
>     libpulseaudio
>   ];
> 
>   LD_LIBRARY_PATH = "${pkgs.stdenv.cc.cc.lib}/lib:${pkgs.libglvnd}/lib:${pkgs.libpulseaudio}/lib";
> }
> ```

It worked.

**Comment by jozefcifre** [comment]
Hmm, is there any documentation on the game engine?

**Comment by Cervator** [comment]
@jozefcifre sort of - we have a fair amount of stuff in the wiki: https://github.com/MovingBlocks/DestinationSol/wiki

I don't think it is going to cover any OS-level quirks or troubleshooting though - just fairly general Java dev and related :-)

Alternatively if you mean LibGDX or LWJGL then yeah they have huge websites of their own to cover probably about anything.

**Comment by jozefcifre** [comment]
> @jozefcifre sort of - we have a fair amount of stuff in the wiki: https://github.com/MovingBlocks/DestinationSol/wiki
> 
> I don't think it is going to cover any OS-level quirks or troubleshooting though - just fairly general Java dev and related :-)
> 
> Alternatively if you mean LibGDX or LWJGL then yeah they have huge websites of their own to cover probably about anything.

That's what I meant, thank you.
