### ISSUE TITLE
Unable to run the Physics Body Editor, due to missing libraries

### ISSUE THREAD

**Issue by jozefcifre** [MovingBlocks/DestinationSol#696]
### What you were trying to do

Sorry if this is not the right place to ask about this issue, but I couldn't find the repository, I could just find an archived repo. https://github.com/selimanac/physics-body-editor

I've been trying to run the jar file of this source: https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/box2d-editor/physics-body-editor-2.9.2.zip

### What actually happened

```
error: undefined variable 'libgdx'
error: undefined variable 'lwjgl'
```

AFAIK, these packages aren't available in the NixOS Channels. 

Do you have any suggestions or know of an alternative way to install them?

### Game version

2.1.0 (develop)

### Operating System

Linux

### Additional Info

I switched to the `nixos-unstable` channel (a rolling release) because it has more available packages, but it seems that it's missing those libraries.

I've tried to run the jar file in a nix-shell, didn't work either.

```nix
# shell.nix

let
  nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-unstable";
  pkgs = import nixpkgs { config = {}; overlays = []; };
in

pkgs.mkShell {
  packages = with pkgs; [
    temurin-bin-11
    glibc
    libgdx
    lwjgl
  ];

  LD_LIBRARY_PATH = "${pkgs.stdenv.cc.cc.lib}/lib:${pkgs.libglvnd}/lib:${pkgs.libpulseaudio}/lib";
}

```

**Comment by BenjaminAmos** [comment]
This project does have a forked version of the Box2D editor but it is actually https://github.com/MovingBlocks/box2d-editor.

The binary jars have just worked for a long time, so the gradle build on that repository got a bit outdated. I've brought it up-to-date in the `gradlew-libgdx-upgrade` branch.

A new `shell.nix` that appears to work:
```nix
let
  nixpkgs = fetchTarball "https://github.com/NixOS/nixpkgs/tarball/nixos-23.05";
  pkgs = import nixpkgs { config = {}; overlays = []; };
in

pkgs.mkShell {
  packages = with pkgs; [
    git
    temurin-bin-11
    libglvnd
    libpulseaudio
    xorg.libXcursor
    xorg.libXrandr
    xorg.libXxf86vm
  ];

  LD_LIBRARY_PATH = "${pkgs.stdenv.cc.cc.lib}/lib:${pkgs.libglvnd}/lib:${pkgs.libpulseaudio}/lib:${pkgs.xorg.libXcursor}/lib:${pkgs.xorg.libXrandr}/lib:${pkgs.xorg.libXxf86vm}/lib";
}
```

When in the nix shell environment, you should be able to run the editor like this:
 -  `git clone https://github.com/MovingBlocks/box2d-editor -b gradle-libgdx-upgrade`
 - `cd box2d-editor`
 - `./gradlew :editor:run`

As an advance warning, the editor is unable to edit existing ship json files (they use a modified JSON layout). Other than that, https://github.com/MovingBlocks/DestinationSol/wiki/Creating-Collision-Meshes is still relevant.

**Comment by BenjaminAmos** [comment]
If you've found issues with the game (crashes, bugs, etc.) then raising an issue here is the right place. If you need more general help with troubleshooting then we share a Discord server with the Terasology project ([join link](https://discord.gg/Terasology)) that can sometimes get a more realtime response (in the `#destination-sol` channel), if you find that easier.

**Comment by jozefcifre** [comment]
> When in the nix shell environment, you should be able to run the editor like this:
> 
>     * `git clone https://github.com/MovingBlocks/box2d-editor -b gradle-libgdx-upgrade`
> 
>     * `cd box2d-editor`
> 
>     * `./gradlew :editor:run`
> 
> 
> As an advance warning, the editor is unable to edit existing ship json files (they use a modified JSON layout). Other than that, https://github.com/MovingBlocks/DestinationSol/wiki/Creating-Collision-Meshes is still relevant.


Hmm, I just encountered an error:

[nix-shell:~/.../box2d-editor]$ ./gradlew :editor:run
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain

**Comment by jozefcifre** [comment]
Thank you for your help.

Btw, I've just found an issue with the `box2d-editor`: https://github.com/MovingBlocks/box2d-editor/issues/48#issue-1989448781

**Comment by BenjaminAmos** [comment]
This was resolved in https://github.com/MovingBlocks/box2d-editor/issues/48#issuecomment-1807177444.
