### ISSUE TITLE
No Error If Game Can't Start

### ISSUE THREAD

**Issue by SimonC4** [MovingBlocks/DestinationSol#71]
If the game can't start, e.g. from an incompatible graphics card, then there isn't any feedback to the user as to the reason why. 

This is reproducible on a Windows 8 or Windows 10 Virtualbox on Mac as they don't support OpenGL.

A few issues reported on steam http://steamcommunity.com/app/342980/discussions/0/535152511351179199/

**Comment by Cervator** [comment]
For a bit of related inspiration there is a pretty sophisticated graphics error handling system in Terasology on startup, @emanuele3d knows it well. It might be useful here as well.

Beyond that we have the CrashReporter project to better handle errors, upload logs, etc, but that may be overkill.

**Comment by Cervator** [comment]
Maybe we can cover this one too while we're at it: http://steamcommunity.com/app/342980/discussions/0/535152511346248564/

I *think* it relates to somehow ending up with invalid graphics config in settings.ini then causing the game to crash on startup. Could the Steam Cloud Saving thing be involved, if you run the game on one device, set a specific resolution, then run the game again on a different system that doesn't support that resolution?

Probably that sort of setting should be excluded if that indeed was carried over by a Steam Save, and that would be a different bug. But catching/reporting it better could perhaps be done here.

**Comment by SimonC4** [comment]
Steam cloud save is only set to save prevShip.ini, so it shouldn't have been that.

There shouldn't be a way that the user can set the configuration to something the graphics card doesn't support, and especially not on the first run. My guess is the user had previously run the game when it was possible to set the resolution to the incorrect setting. Deleting the game removes it from your steam library, but doesn't remove all of the game files, so that was probably left over. 

That aside, I still think that would be good to catch this issue.

My plan was just to do something simple, e.g. pop up a message box with an error. At least provide some kind of feedback. I'm happy if someone else wants to do something more sophisticated though.

**Comment by Cervator** [comment]
Ahh okay, that makes perfect sense now :-)

I dug up the basic checking of OpenGL capabilities in Terasology: https://github.com/MovingBlocks/Terasology/blob/develop/engine/src/main/java/org/terasology/engine/subsystem/lwjgl/LwjglGraphics.java#L268 - thought it might be useful

**Comment by Cervator** [comment]
Closing as fixed. We can always get fancier later :-)
