### ISSUE TITLE
Add functionality to generate prevShip.ini if it doesn't exist

### ISSUE THREAD

**Issue by Rulasmur** [MovingBlocks/DestinationSol#78]
Simple copy it from the res file at runtime or something. So that we can ignore the fscking file. Keep forgetting to remove it from my commits >.>

**Comment by SimonC4** [comment]
The file's not actually needed and it's not included in the distribution build. We can probably add this to the git ignore file now. @Cervator what are your thoughts?

**Comment by Cervator** [comment]
I think we just never got around to taking it out / straightening out the .gitignore. That or kept it around for easier debugging? I'm happy to toss it if all tests out fine.

**Comment by Cervator** [comment]
Closing as complete! Outright deleted both files with them added to .gitignore
