### ISSUE TITLE
system resolution detection not listing max res

### ISSUE THREAD

**Issue by josh-d-dotson** [MovingBlocks/DestinationSol#79]
OS: PCLinuxOS, 64bit, KDE
Monitor: 1080p (1920x1080)
Game ver: 1.0.2

As I run a 64bit system, I cannot use the pre-compiled java. This may account for the detection routine not functioning correctly.

max res selectable in game: 1366x768
To achieve 1080p I had to input the resolution into the settings.ini manually.

**Comment by Cervator** [comment]
Heyo. We talked on IRC some too. Did you get a chance to try out a later game version? Which seems to be the likely culprit :-)

**Comment by Cervator** [comment]
Closing from earlier understanding that this is a game version issue, unless there are any further questions - feel free to re-open / submit something else if so :-)
