### ISSUE TITLE
Game crash from failing to initialize audio device

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#84]
Reported via Steam:http://steamcommunity.com/app/342980/discussions/1/611698195147641156/?tscn=1452510295#c451850468368003299

We've seen similar situations in the past with Terasology and it seems a common issue in general, see for instance https://bugs.mojang.com/browse/MCL-169 for similar issues with Minecraft. In this case the user can oddly enough run both Minecraft and Terasology with working sound. Maybe a difference between LWJGL and LibGDX's use of OpenAL?

Could also be that our code doesn't handle the failure as gracefully as it could. Maybe we can't fix the audio device (without an OpenAL upgrade or some similar bug fix) but at least we should be able to just disable sound and warn the user, but continue.

**Comment by SimonC4** [comment]
It looks like it's an issue with the surround sound. I'll post a workaround to the steam discussion to see if it works. 

libGDX is still using lwjgl 2, which doesn't have much support. I'm not sure we'll be able to do much until libGDX supports lwjgl 3. Does't look like there's much progress on this.

**Comment by hauzer** [comment]
Hey, I'm the guy who reported this on Steam.

My setup is a bit unorthodox, but I had no problem with any other program thus far. I have two sound cards:
* Creative Sound Blaster Live CT4830, using drivers from [kX Project](http://www.kxproject.com/)
* MSI FM2-A55M-E33 integrated, using drivers from AMD CCC

Also, I'm using [Aster](http://www.ibik.ru/) to segregate the two sounds cards (and other peripherals) into one workspace each. The game works on neither of those two workspaces.

Regarding the suggested workaround from Steam:
>For a workaround, assuming you're in Windows, in the sound panel right click on your device and click "Configure Speakers". Try changing your device from "Surround" to "5.1 Surround" or "Stereo".

Both of the workspaces already use stereo.

Hope this helps.

**Comment by SimonC4** [comment]
Interesting. From your error log it would appear that it's trying to configure your audio as 7.1, as the following lines say there are 8 channels. 

```bash
AL lib: (EE) DoReset: Unhandled channel config: 8 -- 0x000000ff
AL lib: (EE) DoReset: Unhandled extensible channels: 8 -- 0x000000ff
```

Someone else has reported a similar issue with the kX driver and OpenAL. Could you try what they suggest in [this link](https://bugs.mojang.com/browse/MCL-169?focusedCommentId=194227&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-194227)

**Comment by hauzer** [comment]
Setting the default device from Master Mixer to Wave Out 2/3 worked.

**Comment by Cervator** [comment]
Thanks for following up, @hauzer :-)

I wonder if we can still harden the game to avoid a crash. Might be tricky if it happens within LWJGL, all we do is:

```java
new LwjglApplication(new SolApplication(), c);
```

Since failing to initialize sound shouldn't technically be fatal maybe we can catch `org.lwjgl.openal.OpenALException` and retry with a soundless configuration? Revealing some angry looking "WARNING: Sound disabled - <error>" in the game UI or so.

**Comment by NicholasBatesNZ** [comment]
Closing this since it's probably not relevant anymore after LWJGL updates and such.
:wave: @hauzer If you'd like then feel free to re-test the latest changes and re-open this if it still occurs
