### ISSUE TITLE
Add option for frame limiting

### ISSUE THREAD

**Issue by Cervator** [MovingBlocks/DestinationSol#94]
I noticed my GPU goes up to 100% usage when running the game, even with the menu up and me working some window outside the game. Am expecting this is from no frame limiting in place although it would be good if somebody else could confirm/theorize.

Terasology has a frame limiter option that will accept up to 200 fps or even disable the limit. We should probably add something similar to DS, defaulted to 60 fps.

**Comment by SimonC4** [comment]
I remember having this issue too and then discovered this line: https://github.com/MovingBlocks/DestinationSol/blob/develop/desktop/src/org/destinationsol/desktop/SolDesktop.java#L34

It would appear that running the game in "devBuild" mode removes the frame rate limiting. I believe that libGDX should limit it to 60 fps in normal mode. This can be probably be confirmed by setting showFps=true in debugOptions.ini.

**Comment by Cervator** [comment]
Ahhhh - nice catch!

We should probably take that out then and just leave a note in dev instructions somewhere should somebody need limitless FPS for some reason. Still would be nice to have an in-game option but not nearly as high priority in that case :-)

**Comment by Adrijaned** [comment]
Seems this somehow got fixed over time (see https://github.com/MovingBlocks/DestinationSol/blob/develop/desktop/src/main/java/org/destinationsol/desktop/SolDesktop.java#L104)
