### ISSUE TITLE
Conversion of inventory system to numerical list

### ISSUE THREAD

**Issue by Rulasmur** [MovingBlocks/DestinationSol#95]
Items would be assigned slot numbers, ie 1-100 are equipped items, and 100+ are inventory items. This will allow us to have an inventory that the player can sort as they like in the future.

**Comment by crazywolf132** [comment]
Would this be similar to the way that minecraft does it? In the way that every item or such is referred to as a number?

**Comment by Cervator** [comment]
Closing from age / finally closing in on full entity-system implementation which will make this obsolete. I think inventory improvements have happened in the meantime anyway :-)
